# Generated by Django 5.2.3 on 2025-06-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='accepted',
            new_name='is_accepted',
        ),
    ]
